name: social_media_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.10.4

dependencies:
  cloud_firestore: ^6.1.2
  cloudinary: ^1.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter_dotenv: ^6.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
